version: '3'
services:

  inx-groupfi:
    container_name: ${INX_GROUPFI_LEDGER_NETWORK:?INX_GROUPFI_LEDGER_NETWORK is missing}-inx-groupfi
    image: dltgreen/inx-groupfi:${INX_GROUPFI_VERSION:?INX_GROUPFI_VERSION is missing}
    stop_grace_period: 5m
    restart: unless-stopped
    user: "65532"
    ulimits:
      nofile:
        soft: 16384
        hard: 16384
    command: [ "--config", "/app/config/config.json" ]
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${INX_GROUPFI_DATA_DIR:-./data}/config/config-${INX_GROUPFI_NETWORK:-mainnet}.json:/app/config/config.json:ro"
      - "${INX_GROUPFI_DATA_DIR:-./data}/database/${INX_GROUPFI_NETWORK:-mainnet}:/database"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"

networks:
  default:
    name: ${INX_GROUPFI_LEDGER_NETWORK:?INX_GROUPFI_LEDGER_NETWORK is missing}
    external: true
